title: Ananth Sridev
author:
    name: Ananth Sridev
    email: m.ananthsridev@gmail.com
metadata:
    description: 'Data-driven Digital Marketing Specialist with 8+ years of expertise in SEO, performance marketing, GA4, GTM, and marketing automation.'
taxonomies: [category, tag]
